### ISSUE TITLE
CLIP Blog Last Code Bit

### ISSUE THREAD

**Issue by shenoynikhil** [amaarora/amaarora.github.io#15]
Hey Aman,

Great blog and reads really well. I had a question regarding the last part of the pseudo-code provided,
```python
labels = np.arange(n)  # will be something like (0, 1, 2, 3, ...., n - 1) shape (n, )
loss_i = cross_entropy_loss(logits, labels, axis=0)  # logits are shaped (n, n)
loss_t = cross_entropy_loss(logits, labels, axis=1) 
loss = (loss_i + loss_t)/2
```
Can you maybe explain how this enables the cosine similarity to be high along the diagonal and low along off-diagonal elements? I added some comments on the side for my own understanding.

Also, a suggestion would be to enable comments, so that people having similar doubts can look at the comments.

**Comment by amaarora** [comment]
Thank you @shenoynikhil 

I would recommend this video here https://youtu.be/p4ZZq0736Po?t=2796
